### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Victoria-Gonzalez-Instagram#1]
# Revisión - Aprobado
- [x] Estilo de código y limpieza
# Feedback
- ¡Buen trabajo. Felicidades @Vickygonrod  !
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- En el index.html, hay un cierre de etiqueta `</img>` que no es necesario, ya que la etiqueta `<img>` no necesita cerrarse explícitamente.
![Captura de pantalla de 2024-03-07 19-26-08](https://github.com/4GeeksAcademy/Victoria-Gonzalez-Instagram/assets/139759297/adddb091-17b4-4cb5-b7e3-d8977159bd9e)

                         `<img src="https://loremflickr.com/340/340">`  

- Te invito a que intentes arreglar esta parte del proyecto 

![Captura de pantalla de 2024-03-07 19-29-17](https://github.com/4GeeksAcademy/Victoria-Gonzalez-Instagram/assets/139759297/6095b3a4-a37f-4903-9c31-4798fb404705)

y dejarlo más parecido al proyecto propuesto 
![Captura de pantalla de 2024-03-07 19-29-27](https://github.com/4GeeksAcademy/Victoria-Gonzalez-Instagram/assets/139759297/06134105-dff1-481c-8a57-00fa532b0076)

**Comment by Vickygonrod** [comment]
OK! Lo arreglo! :) Gracias Edo!

**Comment by EduardoHernandezGuzman** [comment]
Muy buen trabajo Victoria... a por el siguiente!!!
